[workspace]
authors = ["Mike Xiangyu Liu <liu.xiangyu@ucy.ac.cy>"]
channels = ["conda-forge"]
name = "mesa"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-jrl = { cwd = "deps/jrl", cmd = "mkdir -p build && cd build && cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DJRL_BUILD_PYTHON=ON -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX && make -j10 && make install && make jrl-python-install" }
build = { cmd = "mkdir -p build && cd build && cmake .. -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release && ninja" }
build-gtsam = { cmd = "cd deps/gtsam && mkdir -p build && cd build && cmake .. -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_USE_SYSTEM_METIS=ON -DGTSAM_BUILD_EXAMPLES_ALWAYS=OFF -DGTSAM_BUILD_TESTS=OFF -DGTSAM_BUILD_PYTHON=ON -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX && make -j10 && make install && make python-install" }
# Visualization and development tasks
jupyter = { cmd = "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root" }
notebook = { cmd = "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root" }

[tasks.plot-results]
cmd = "python scripts/plot-results -d data/results/jrl/{{ d }}.jrl -r data/results/seq/{{ r }} --is3d"
args = [
  { "arg" = "d", "default" = "input_MITb_g2o_3d" },
  { "arg" = "r", "default" = "input_MITb_g2o_3d_dgs_2025-08-06_14-58-24/final_results.jrr.cbor" },
]

[tasks.plot-jrl]
cmd = "python scripts/plot-jrl data/results/jrl/{{ d }}.jrl --is3d"
args = [
  { "arg" = "d", "default" = "input_MITb_g2o_3d" },
]


[dependencies]
numpy = "*"
matplotlib = "*"
scipy = "*"
setuptools = "*"
ninja = ">=1.13.1,<2"
cmake = "<4"
pip = "*"
seaborn = "*"
# Visualization dependencies
plotly = "*"
jupyter = "*"
jupyterlab = "*"
ipywidgets = "*"
bokeh = "*"
pandas = "*"
# OpenGL and graphics support
mesa-libgl-cos6-x86_64 = "*"
mesa-dri-drivers-cos6-x86_64 = "*"
